### ISSUE TITLE
Final Fantasy XIII Update Incompatibility

### ISSUE THREAD

**Issue by shinra358** [PeterTh/gedosato#249]
Coverage Sampling causes black screen.

Launching the game from the launcher causes the story words not to show on the loading screen.

Gedosato Borderless Window broken. Game won't start.

autohotkey borderless window broken too. tiny picture with rest of the screen black.

Edit: Everything above is with running the launcher first. Looks like I can use everything from Gedo without issue except Gedo borderless without running the launcher first (start game from bare exe). I would have to use autohotkey for the borderless tho.

**Comment by karasuhebi** [comment]
@Drakonas Oh wow, I feel dumb now. Looking at your .ini I noticed that I was using the wrong value for enableCoverageSampling. I had it set to true and figured GeDoSaTo would take it from there. I didn't realize I had to specify which one I needed. Oops. XD

@PeterTh Is there a way to have GeDoSaTo show you if a certain setting is enabled or disabled so that I can make sure I'm setting the right values for them? When I press VK_ADD all I get is the downsampling info and the AA and post-processing info.
