### ISSUE TITLE
GeDoSaTo Doing Nothing

### ISSUE THREAD

**Issue by Travis-Cassity** [PeterTh/gedosato#315]
Heyy. Program isn't doing anything for me. Nothing at all. Hotkeys do nothing, settings do nothing. Spamming screenshot hotkeys, "show hud", etc, and nothing is happening. As far as I can tell, the program is not interacting at all with anything I launch it with.

Started when I updated to the "Chaos Flare" version. Attempted a fresh install and still had this problem.

**Comment by pokeguru87** [comment]
I'm having the same issue. It worked with the previous version, but after updating to 0.19.1947 it stopped loading. I'm only really trying to use it for Tales of Zestiria, if that makes any difference.

**Comment by DaimyoValk** [comment]
I was having the same issue as well. In order to fix it, I had to reinstall to C:\GeDoSaTo instead of my typical C:\Program Files (x86)\GeDoSaTo.

Although this had led to a unique issue with only Tales of Zestiria for me. When GeDoSaTo is open, ToS won't even load the splash screen and puts this error.txt in its directory:

"Could not read the install location from the registry.
Make sure to extract the downloaded files to a suitable location and run GeDoSaToTool.exe"

I can run any other game fine with GeDoSaTo though.

**Comment by pokeguru87** [comment]
I have it installed to C:\GeDoSaTo

That is where I've always installed it. Also I'm using Windows 10 with a GTX 980 Ti.

**Comment by DaimyoValk** [comment]
Have you tried a fresh install since the update? A lot of people had issues with the updater.

**Comment by pokeguru87** [comment]
Multiple times and into different folders, all of which were in my base C: drive.

**Comment by MSxDOS** [comment]
I confirm, 1947 isn't working at all here on Win 7 x64. It simply doesn't inject to any of the whitelisted processes.

**Comment by Sammeal** [comment]
Problem mirrors my own. No injection to any whitelisted applications. Does not matter where it is installed. All prereqs are good to go. 

Nvidia GTX 970m | Windows 10 ASUS laptop.

**Comment by jsangeorzan** [comment]
Have same issues.

Windows 10 x 64, previous version worked fine.  I fully deleted/rebooted and reinstalled, no dice.

**Comment by PeterTh** [comment]
I'll close this as I'll create a separate issue.
